import './xlazz.css';
//import './bootstrapfix.scss';
import './landing.scss';
import './nav.scss';
import './footer.scss';
import './timers.scss';
import './activeclock.scss';
import './layout.scss';
import './bootstrap-tagsinput.scss';
